# Generated by CMake, DO NOT EDIT
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/build.debug/build.arm/CMakeFiles/cmake.check_cache: \
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/CMakeLists.txt\
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/build.debug/build.arm/CMakeFiles/3.3.2/CMakeCCompiler.cmake\
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/build.debug/build.arm/CMakeFiles/3.3.2/CMakeCXXCompiler.cmake\
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/build.debug/build.arm/CMakeFiles/3.3.2/CMakeSystem.cmake\
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/ios-cmake/toolchain/iOS.cmake\
/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/opt/CMakeLists.txt\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeCInformation.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeCXXInformation.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeCommonLanguageInclude.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeForceCompiler.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeGenericSystem.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/Platform/Darwin-Initialize.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/Platform/Darwin-clang.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/Platform/Darwin.cmake\
/usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/Platform/UnixPaths.cmake
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example -B/Users/bernardtaloza/Documents/cppworks/opensource/cpr-example/build_ios/build.debug/build.arm
